<a href="https://colab.research.google.com/github/Srdcf/HAR/blob/main/modeloHAR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
# import required libraries
import pandas as pd
import numpy as np
import seaborn as sns

import torch

from sklearn.metrics import f1_score, accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split



In [ ]:
#df = pd.read_csv('/content/drive/MyDrive/dataset1.csv')
df = pd.read_csv('/content/drive/MyDrive/dataset2.csv')


In [ ]:
df

Unnamed: 0  Latitude Change  Longitude Change  Altitude Change  \
0                0              0.0               0.0              0.0   
1                1              0.0               0.0              0.0   
2                2              0.0               0.0              0.0   
3                3              0.0               0.0              0.0   
4                4              0.0               0.0              0.0   
...            ...              ...               ...              ...   
119860      119860              0.0               0.0              0.0   
119861      119861              0.0               0.0              0.0   
119862      119862              0.0               0.0              0.0   
119863      119863              0.0               0.0              0.0   
119864      119864              0.0               0.0              0.0   

        Horizontal Accuracy Change  Speed Change  Gyroscope X  Gyroscope Y  \
0                              0.0           0.0    -0.063781     0.059786   
1                              0.0           0.0    -0.042476     0.115178   
2                              0.0           0.0     0.053395     0.148067   
3                              0.0           0.0    -0.029693     0.114113   
4                              0.0           0.0    -0.072303     0.098135   
...                            ...           ...          ...          ...   
119860                         0.0           0.0    -0.023435    -0.042742   
119861                         0.0           0.0    -0.056324    -0.040612   
119862                         0.0           0.0    -0.037150     0.020106   
119863                         0.0           0.0     0.005326     0.062716   
119864                         0.0           0.0     0.036218    -0.002264   

        Gyroscope Z  Acceleration X Change  Acceleration Y Change  \
0          0.006924               0.000000               0.000000   
1          0.101730               0.000000               0.000000   
2          0.123034               0.000000               0.000000   
3          0.088947               0.000000               0.000000   
4          0.113447               0.000000               0.000000   
...             ...                    ...                    ...   
119860     0.042876               0.172020               0.885110   
119861    -0.006125               0.453840               0.153720   
119862    -0.095605              -0.634095              -0.175680   
119863    -0.018908              -0.293410              -0.297985   
119864     0.090811              -0.414800               0.690825   

        Acceleration Z Change  Roll (º)  Pitch (º)   Yaw (º)  \
0                    0.000000 -19.75767  -11.26569  0.944726   
1                    0.000000 -19.66945  -11.03860  0.851585   
2                    0.000000 -19.68774  -10.73308  0.631760   
3                    0.000000 -19.80198  -10.73826  0.417986   
4                    0.000000 -19.72018  -10.74029  0.188188   
...                       ...       ...        ...       ...   
119860              -0.186050   0.00000    0.00000  0.000000   
119861              -0.135421   0.00000    0.00000  0.000000   
119862              -0.034160   0.00000    0.00000  0.000000   
119863              -0.127490   0.00000    0.00000  0.000000   
119864              -0.132370   0.00000    0.00000  0.000000   

        Magnetometer X Change  Magnetometer Y Change  Magnetometer Z Change  \
0                    0.000000                0.00000                0.00000   
1                    0.000000                0.00000                0.00000   
2                    0.000000                0.00000                0.00000   
3                    0.000000                0.00000                0.00000   
4                    0.000000                0.00000                0.00000   
...                       ...                    ...                    ...   
119860              -1.199999  

In [ ]:
# Encode categorical labels
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
df['DataLabelEncoder'] = label_encoder.fit_transform(df['DataLabel'])

In [ ]:
# Get the mapping of original classes to their corresponding numerical values
class_mapping = dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_)))

print("Class to Label mapping:")
print(class_mapping)


Class to Label mapping:
{'Moving': 0, 'idle': 1, 'picking': 2}


In [ ]:

# Split the data into features and target
X = (df.loc[:, 'Latitude Change':'Speed Change']).join(df.loc[:, 'Gyroscope X':'Gyroscope Z']).join(df.loc[:, 'Acceleration X Change':'Acceleration Z Change']).join(df.loc[:, 'Roll (º)':'Yaw (º)']).join(df.loc[:, 'Magnetometer X Change':'Magnetometer Z Change'])

y = df['DataLabelEncoder']  # Target

In [ ]:
X


Latitude Change  Longitude Change  Altitude Change  \
0                   0.0               0.0              0.0   
1                   0.0               0.0              0.0   
2                   0.0               0.0              0.0   
3                   0.0               0.0              0.0   
4                   0.0               0.0              0.0   
...                 ...               ...              ...   
119860              0.0               0.0              0.0   
119861              0.0               0.0              0.0   
119862              0.0               0.0              0.0   
119863              0.0               0.0              0.0   
119864              0.0               0.0              0.0   

        Horizontal Accuracy Change  Speed Change  Gyroscope X  Gyroscope Y  \
0                              0.0           0.0    -0.063781     0.059786   
1                              0.0           0.0    -0.042476     0.115178   
2                              0.0           0.0     0.053395     0.148067   
3                              0.0           0.0    -0.029693     0.114113   
4                              0.0           0.0    -0.072303     0.098135   
...                            ...           ...          ...          ...   
119860                         0.0           0.0    -0.023435    -0.042742   
119861                         0.0           0.0    -0.056324    -0.040612   
119862                         0.0           0.0    -0.037150     0.020106   
119863                         0.0           0.0     0.005326     0.062716   
119864                         0.0           0.0     0.036218    -0.002264   

        Gyroscope Z  Acceleration X Change  Acceleration Y Change  \
0          0.006924               0.000000               0.000000   
1          0.101730               0.000000               0.000000   
2          0.123034               0.000000               0.000000   
3          0.088947               0.000000               0.000000   
4          0.113447               0.000000               0.000000   
...             ...                    ...                    ...   
119860     0.042876               0.172020               0.885110   
119861    -0.006125               0.453840               0.153720   
119862    -0.095605              -0.634095              -0.175680   
119863    -0.018908              -0.293410              -0.297985   
119864     0.090811              -0.414800               0.690825   

        Acceleration Z Change  Roll (º)  Pitch (º)   Yaw (º)  \
0                    0.000000 -19.75767  -11.26569  0.944726   
1                    0.000000 -19.66945  -11.03860  0.851585   
2                    0.000000 -19.68774  -10.73308  0.631760   
3                    0.000000 -19.80198  -10.73826  0.417986   
4                    0.000000 -19.72018  -10.74029  0.188188   
...                       ...       ...        ...       ...   
119860              -0.186050   0.00000    0.00000  0.000000   
119861              -0.135421   0.00000    0.00000  0.000000   
119862              -0.034160   0.00000    0.00000  0.000000   
119863              -0.127490   0.00000    0.00000  0.000000   
119864              -0.132370   0.00000    0.00000  0.000000   

        Magnetometer X Change  Magnetometer Y Change  Magnetometer Z Change  
0                    0.000000                0.00000                0.00000  
1                    0.000000                0.00000                0.00000  
2                    0.000000                0.00000                0.00000  
3                    0.000000                0.00000                0.00000  
4                    0.000000                0.00000                0.00000  
...                       ...                    ...                    ...  
119860              -1.199999               -0.88125                0.80625  
119861              -1.331250               -0.95625                0.91875  
119862              -0.843

In [ ]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [ ]:
import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.callbacks import LearningRateScheduler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
input_shape = X.shape[1]
model = models.Sequential([
    layers.Dense(512, activation='relu', input_shape=(input_shape,)),
    layers.Dropout(0.4),
    layers.Dense(256, activation='relu'),
    layers.Dropout(0.4),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.4),
    layers.Dense(64, activation='relu'),
    layers.Dropout(0.4),
    layers.Dense(3, activation='softmax')
])

initial_learning_rate = 0.001
opt = tf.keras.optimizers.Adam(learning_rate=initial_learning_rate)
def lr_schedule(epoch):
    return initial_learning_rate * 0.95 ** epoch

lr_scheduler = LearningRateScheduler(lr_schedule)

model.compile(optimizer=opt,
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

history = model.fit(X, y, epochs=70, batch_size=128, callbacks=[lr_scheduler])

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/70
937/937 ━━━━━━━━━━━━━━━━━━━━ 11s 9ms/step - accuracy: 0.5017 - loss: 2.0570 - learning_rate: 0.0010
Epoch 2/70
937/937 ━━━━━━━━━━━━━━━━━━━━ 11s 10ms/step - accuracy: 0.6073 - loss: 0.8043 - learning_rate: 9.5000e-04
Epoch 3/70
937/937 ━━━━━━━━━━━━━━━━━━━━ 11s 11ms/step - accuracy: 0.6224 - loss: 0.7622 - learning_rate: 9.0250e-04
Epoch 4/70
937/937 ━━━━━━━━━━━━━━━━━━━━ 11s 12ms/step - accuracy: 0.6281 - loss: 0.7414 - learning_rate: 8.5737e-04
Epoch 5/70
937/937 ━━━━━━━━━━━━━━━━━━━━ 19s 11ms/step - accuracy: 0.6345 - loss: 0.7293 - learning_rate: 8.1451e-04
Epoch 6/70
937/937 ━━━━━━━━━━━━━━━━━━━━ 10s 11ms/step - accuracy: 0.6422 - loss: 0.7160 - learning_rate: 7.7378e-04
Epoch 7/70
937/937 ━━━━━━━━━━━━━━━━━━━━ 8s 9ms/step - accuracy: 0.6456 - loss: 0.7095 - learning_rate: 7.3509e-04
Epoch 8/70
937/937 ━━━━━━━━━━━━━━━━━━━━ 11s 12ms/step - accuracy: 0.6462 - loss: 0.7046 - learning_rate: 6.9834e-04
Epoch 9/70
937/937 ━━━━━━━━━━━━━━━━━━━━ 18s 9ms/step - accuracy: 0.6503 - loss:

In [ ]:
model.evaluate(X_test, y_test, batch_size=128, verbose=1)

NameError: name 'X_test' is not defined

In [ ]:
import numpy as np
from sklearn.metrics import confusion_matrix

# Get predictions from the model
y_pred = np.argmax(model.predict(X_test), axis=1)

# Create confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)

print("Confusion Matrix:")
print(conf_matrix)


815/815 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step
Confusion Matrix:
[[11443    15  2174]
 [ 2075   364   123]
 [ 6188     2  3686]]


In [ ]:
import numpy as np

# Matriz de confusão original
confusion_matrix = np.array([
    [38696, 50, 6614],
    [5588, 2257, 760],
    [18595, 25, 14315]
])

# Calcular a soma total de todos os elementos da matriz
total_sum = np.sum(confusion_matrix)

# Converter cada valor para porcentagem
confusion_matrix_percent = (confusion_matrix / total_sum) * 100

# Arredondar os valores para 2 casas decimais e garantir que não use notação científica
confusion_matrix_percent_rounded = np.round(confusion_matrix_percent, 2)

# Formatar a matriz para exibir os valores corretamente
np.set_printoptions(suppress=True, precision=2)

print("Matriz de Confusão em Porcentagens:")
print(confusion_matrix_percent_rounded)

Matriz de Confusão em Porcentagens:
[[44.53  0.06  7.61]
 [ 6.43  2.6   0.87]
 [21.4   0.03 16.47]]


In [ ]:
model.save('harModel.h5')